grails-app/domain/org/translight/Word.groovy
package org.translight

class Word {

    static scaffold = true

    String originalText
    String translatedText
    Language originalLanguageId
    Language translatedLanguageId
    TranslateEngine translateEngine
    Date dateCreated

    static constraints = {
    }

}

grails-app/controllers/org/translight/WordController.groovy
package org.translight

class WordController {

    static scaffold = true

    def create() {
        request.setAttribute("languages", Language.getAll())
        request.setAttribute("translateEngines", TranslateEngine.getAll())
    }
}

grails-app/views/word/_form.gsp
<%@ page import="org.translight.Word" %>



<div class="fieldcontain ${hasErrors(bean: wordInstance, field: 'originalLanguageId', 'error')} required">
    <label for="originalLanguageId">
        <g:message code="word.originalLanguageId.label" default="Original Language Id"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="originalLanguageId" name="originalLanguageId.id" from="${org.translight.Language.list()}"
              optionKey="id" required="" value="${wordInstance?.originalLanguageId?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: wordInstance, field: 'originalText', 'error')} required">
    <label for="originalText">
        <g:message code="word.originalText.label" default="Original Text"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="originalText" required="" value="${wordInstance?.originalText}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: wordInstance, field: 'translateEngine', 'error')} required">
    <label for="translateEngine">
        <g:message code="word.translateEngine.label" default="Translate Engine"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="translateEngine" name="translateEngine.id" from="${org.translight.TranslateEngine.list()}"
              optionKey="id" required="" value="${wordInstance?.translateEngine?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: wordInstance, field: 'translatedLanguageId', 'error')} required">
    <label for="translatedLanguageId">
        <g:message code="word.translatedLanguageId.label" default="Translated Language Id"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="translatedLanguageId" name="translatedLanguageId.id" from="${org.translight.Language.list()}"
              optionKey="id" required="" value="${wordInstance?.translatedLanguageId?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: wordInstance, field: 'translatedText', 'error')} required">
    <label for="translatedText">
        <g:message code="word.translatedText.label" default="Translated Text"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="translatedText" required="" value="${wordInstance?.translatedText}"/>

</div>

grails-app/views/word/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'word.label', default: 'Word')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-word" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-word" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${wordInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${wordInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: wordInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/word/edit.gsp
<%@ page import="org.translight.Word" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'word.label', default: 'Word')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-word" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-word" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${wordInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${wordInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: wordInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${wordInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/word/index.gsp
<%@ page import="org.translight.Word" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'word.label', default: 'Word')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-word" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-word" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="dateCreated"
                              title="${message(code: 'word.dateCreated.label', default: 'Date Created')}"/>

            <th><g:message code="word.originalLanguageId.label" default="Original Language Id"/></th>

            <g:sortableColumn property="originalText"
                              title="${message(code: 'word.originalText.label', default: 'Original Text')}"/>

            <th><g:message code="word.translateEngine.label" default="Translate Engine"/></th>

            <th><g:message code="word.translatedLanguageId.label" default="Translated Language Id"/></th>

            <g:sortableColumn property="translatedText"
                              title="${message(code: 'word.translatedText.label', default: 'Translated Text')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${wordInstanceList}" status="i" var="wordInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${wordInstance.id}">${fieldValue(bean: wordInstance, field: "dateCreated")}</g:link></td>

                <td>${fieldValue(bean: wordInstance, field: "originalLanguageId")}</td>

                <td>${fieldValue(bean: wordInstance, field: "originalText")}</td>

                <td>${fieldValue(bean: wordInstance, field: "translateEngine")}</td>

                <td>${fieldValue(bean: wordInstance, field: "translatedLanguageId")}</td>

                <td>${fieldValue(bean: wordInstance, field: "translatedText")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${wordInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/word/show.gsp
<%@ page import="org.translight.Word" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'word.label', default: 'Word')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-word" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-word" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list word">

        <g:if test="${wordInstance?.dateCreated}">
            <li class="fieldcontain">
                <span id="dateCreated-label" class="property-label"><g:message code="word.dateCreated.label"
                                                                               default="Date Created"/></span>

                <span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate
                        date="${wordInstance?.dateCreated}"/></span>

            </li>
        </g:if>

        <g:if test="${wordInstance?.originalLanguageId}">
            <li class="fieldcontain">
                <span id="originalLanguageId-label" class="property-label"><g:message
                        code="word.originalLanguageId.label" default="Original Language Id"/></span>

                <span class="property-value" aria-labelledby="originalLanguageId-label"><g:link controller="language"
                                                                                                action="show"
                                                                                                id="${wordInstance?.originalLanguageId?.id}">${wordInstance?.originalLanguageId?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${wordInstance?.originalText}">
            <li class="fieldcontain">
                <span id="originalText-label" class="property-label"><g:message code="word.originalText.label"
                                                                                default="Original Text"/></span>

                <span class="property-value" aria-labelledby="originalText-label"><g:fieldValue bean="${wordInstance}"
                                                                                                field="originalText"/></span>

            </li>
        </g:if>

        <g:if test="${wordInstance?.translateEngine}">
            <li class="fieldcontain">
                <span id="translateEngine-label" class="property-label"><g:message code="word.translateEngine.label"
                                                                                   default="Translate Engine"/></span>

                <span class="property-value" aria-labelledby="translateEngine-label"><g:link
                        controller="translateEngine" action="show"
                        id="${wordInstance?.translateEngine?.id}">${wordInstance?.translateEngine?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${wordInstance?.translatedLanguageId}">
            <li class="fieldcontain">
                <span id="translatedLanguageId-label" class="property-label"><g:message
                        code="word.translatedLanguageId.label" default="Translated Language Id"/></span>

                <span class="property-value" aria-labelledby="translatedLanguageId-label"><g:link controller="language"
                                                                                                  action="show"
                                                                                                  id="${wordInstance?.translatedLanguageId?.id}">${wordInstance?.translatedLanguageId?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${wordInstance?.translatedText}">
            <li class="fieldcontain">
                <span id="translatedText-label" class="property-label"><g:message code="word.translatedText.label"
                                                                                  default="Translated Text"/></span>

                <span class="property-value" aria-labelledby="translatedText-label"><g:fieldValue bean="${wordInstance}"
                                                                                                  field="translatedText"/></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: wordInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${wordInstance}"><g:message code="default.button.edit.label"
                                                                                     default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>